
package com.hotel.ws.ricerca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-07T19:16:36.351+01:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "faultString", targetNamespace = "http://www.hotel.com/ricerca/")
public class FaultResponse extends Exception {
    
    private java.lang.String faultString;

    public FaultResponse() {
        super();
    }
    
    public FaultResponse(String message) {
        super(message);
    }
    
    public FaultResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultResponse(String message, java.lang.String faultString) {
        super(message);
        this.faultString = faultString;
    }

    public FaultResponse(String message, java.lang.String faultString, Throwable cause) {
        super(message, cause);
        this.faultString = faultString;
    }

    public java.lang.String getFaultInfo() {
        return this.faultString;
    }
}
