package com.hotel.ws.ricerca;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-12-30T18:03:19.051+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.hotel.com/ws/ricerca/", name = "ricerca")
@XmlSeeAlso({com.hotel.ricerca.ObjectFactory.class, com.hotel.ObjectFactory.class})
public interface Ricerca {

    @ResponseWrapper(localName = "ricercaStanzaResponse", targetNamespace = "http://www.hotel.com/ricerca/", className = "com.hotel.ricerca.RicercaStanzaResponse")
    @RequestWrapper(localName = "ricercaStanza", targetNamespace = "http://www.hotel.com/ricerca/", className = "com.hotel.ricerca.RicercaStanza")
    @WebMethod
    public void ricercaStanza(
        @WebParam(mode = WebParam.Mode.INOUT, name = "sessionId", targetNamespace = "http://www.hotel.com/ricerca/")
        javax.xml.ws.Holder<java.lang.String> sessionId,
        @WebParam(name = "arrivo", targetNamespace = "http://www.hotel.com/ricerca/")
        javax.xml.datatype.XMLGregorianCalendar arrivo,
        @WebParam(name = "partenza", targetNamespace = "http://www.hotel.com/ricerca/")
        javax.xml.datatype.XMLGregorianCalendar partenza,
        @WebParam(name = "stanza", targetNamespace = "http://www.hotel.com/ricerca/")
        com.hotel.Stanza stanza,
        @WebParam(mode = WebParam.Mode.OUT, name = "rispostaHotel", targetNamespace = "http://www.hotel.com/ricerca/")
        javax.xml.ws.Holder<java.util.List<com.hotel.RispostaHotel>> rispostaHotel
    );
}
